name: Select browser and trigger pipeline

on:
  workflow_dispatch:
    inputs:
      browser:
        type: choice
        description: Which browser to test
        required: true
        options:
          - chrome
          - edge
          - firefox
          - safari
          - all
          - local
      cucumber_tags:
        type: string
        description: Filter cucumber tags
        required: false
        default: '@Regression'

jobs:
  trigger-tests:
    uses: CROD37/CBTW-Demo/.github/workflows/chrome_pipeline.yml@main
    with:
      cucumber_tags: ${{ inputs.cucumber_tags }}
      browser: ${{ inputs.browser }}

  update-readme:
    if: always()
    runs-on: ubuntu-latest
    needs: [ trigger-tests-with-chrome, trigger-tests-with-edge, trigger-tests-with-firefox, trigger-tests-with-safari ]
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Make public directory
        run: mkdir public

      - name: Converts Markdown to HTML
        uses: jaywcjlove/markdown-to-html-cli@main
        with:
          source: README.md
          output: public/index.html

      - name: Deploy report to Github Pages
        if: always()
        uses: peaceiris/actions-gh-pages@v3
        with:
          PERSONAL_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          PUBLISH_BRANCH: gh-pages
          PUBLISH_DIR: ./public
          KEEP_FILES: true